-- Fix CRITICAL Supabase advisor: rls_disabled_in_public on public._keepalive
-- Tiny ping / anti-pause helper (not used by app code).
-- CREATE IF NOT EXISTS so fresh Supabase Preview DBs (no manual table) still migrate.

CREATE TABLE IF NOT EXISTS public._keepalive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public._keepalive ENABLE ROW LEVEL SECURITY;
ALTER TABLE public._keepalive FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public._keepalive FROM anon, authenticated;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'S'
      AND c.relname = '_keepalive_id_seq'
  ) THEN
    EXECUTE 'REVOKE ALL ON SEQUENCE public._keepalive_id_seq FROM anon, authenticated';
  END IF;
END
$$;

COMMENT ON TABLE public._keepalive IS
  'Project ping / anti-pause helper; service-role only. RLS enabled with no client policies.';
